kind: Service
apiVersion: v1
metadata:
  name: rng
spec:
  selector:
    app: rng
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng-deployment
  labels:
    app: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: europe-west1-docker.pkg.dev/teolia-school-devops/teolia-school-amineb/rng:0.0.1-dev-b846405c62a6678b5d9cc197b43ec71fae8bf633
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "30Mi"
      nodeSelector:
        app: first

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rng-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rng-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100