kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: europe-west1-docker.pkg.dev/teolia-school-devops/teolia-school-amineb/redis:0.0.1-dev-b846405c62a6678b5d9cc197b43ec71fae8bf633
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "50m"
            memory: "10Mi"
      nodeSelector:
        app: first

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redis-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-server-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100