kind: Service
apiVersion: v1
metadata:
  name: webui-service
spec:
  type: NodePort
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000

---    

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: web
        image: europe-west1-docker.pkg.dev/teolia-school-devops/teolia-school-amineb/webui:v0.0.1-dev-7c857712913b9c932f7224676fb16d1dcaa02cf3
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
      nodeSelector:
        app: second

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100